### PR TITLE
CI / DC using github actions

### PR DESCRIPTION
**Pull request by shafr**

### CODE REVIEW

**Comment by shafr** [comment]
## Description:


This commit introduces CI/DC routines for a project.

Examples build for ESP32 / ESP8266 
Libraries build for ESP32 / ESP8266 
CPP Lint on pull requests
Issue & Pull request template

## Type of change:


- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Testing:


- [X] merged with the current development branch (before testing)
- [ ] CI build finished without issues - issues with examples
- [ ] Tested on real hardware (List board here) - not applicable
- [X] Changes are backward compatible

## Checklist:


- [ ] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

**Comment by shafr** [comment]
Please when you would have time, do 2 actions:
1) Fix examples/ESP32_Ethernet_Send_Text/ESP32_Ethernet_Send_Text.ino - it is using 1.2.1 API, so fails with issue:
```
/tmp/tmp5tonr4ee/src/ESP32_Ethernet_Send_Text.ino:297:27: error: 'SMTP_Result {aka struct esp_mail_smtp_send_status_t}' has no member named 'timesstamp'
       localtime_r(&result.timesstamp, &dt);
                           ^
*** [.pio/build/lolin32/src/ESP32_Ethernet_Send_Text.ino.cpp.o] Error 1
```
2) Rename one of `image.h` files in examples & variable name inside it - so there would be no collision related to the way that  libraries are being tested

**Comment by mobizt** [comment]
I really appreciated and thank for your contribution.

I will check the issue you mention and update.

**Comment by shafr** [comment]
Sure, glad to help.
Just mention me if you'll need help with anything.

Also i really want to include library / sketch size delta (as in arduino delta action) on pull request, but for now i'm lacking js skills for that, so that's next in line.

**Pull request merged**
